baseURL = "http://example.org/"
languageCode = "en-us"
title = "Stream Speed Dial"
theme = "slate"
OpenLinksInNewWindow = false

[[ params.nav ]]
name = "search"
tag = "search"
icon = "search"

[[ params.nav ]]
name = "docs"
tag = "docs"
icon = "book"

[[ params.nav ]]
name = "moredocs"
tag = "moredocs"
icon = "book"


[[ params.nav ]]
name = "twitch"
tag = "twitch"
icon = "twitch"

[[ params.nav ]]
name = "dev"
tag = "dev"
icon = "code"

[[ params.nav ]]
name = "stream"
tag = "stream"
icon = "broadcast-tower"
